set -g default-terminal "screen-256color"

set -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

source-file "${HOME}/.tmux-themepack/powerline/block/cyan.tmuxtheme"
bind r source ~/.tmux.conf\; display "~/.tmux.conf sourced!"

